ansible_user: admin-ubt
ansible_ssh_private_key_file: ~/.ssh/id_ed25519
ansible_python_interpreter: /usr/bin/python3
ansible_connection: ssh
ansible_sshpass_prompt: Enter passphrase for key '/home/kali/.ssh/id_ed25519'
ansible_ssh_pass: admin
ansible_become: true
ansible_become_method: sudo
ansible_become_pass: admin